export const curriculumObjectArray = [
  {
    id: 1,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 2,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 3,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 4,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 5,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 6,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 7,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 8,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 9,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 1,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 2,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 3,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 4,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 5,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 6,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 7,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 8,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
  {
    id: 9,
    icon: "https://res.cloudinary.com/dmrdnero7/image/upload/v1654040523/frontendMentorship/web_icon_lmzcqi.png",
    title: "Introduction to web",
    subText: "25 lessons",
  },
];
